### ISSUE TITLE
REF : Hide the huge header / intro when scrolling down

### ISSUE THREAD

**Issue by MagicFab** [millette/gatsby-starter-location-github#36]
I would be nice to have the big header hide when scrolling down (or permanently after a few visits?), as it's useful to discover the site initially but gets in the way in future searches.

**Comment by millette** [comment]
Indeed. I have a couple of options:

* Move directory to another page (without the header)
* Add a toggle button to the header

I was forced to put the directory on the front page due to a bug I had a month ago, but it's been fix since then, so I can move stuff around.

Merci for your suggestions :-)

**Comment by millette** [comment]
Added a header toggle for now. It's not sticky but it'll do for now.
